DELETE FROM MOBILE
INSERT INTO MOBILE (ID, MODELNAME, OS, BRAND) VALUES (1, 'Honor X', 'Android', 'Honor')
INSERT INTO MOBILE (ID, MODELNAME, OS, BRAND) VALUES (2, 'LG G5', 'Android', 'LG')
INSERT INTO MOBILE (ID, MODELNAME, OS, BRAND) VALUES (3, 'Iphone 8', 'iOS', 'Apple')
INSERT INTO MOBILE (ID, MODELNAME, OS, BRAND) VALUES (4, 'Moto G5S Plus', 'Android', 'Motorola')
INSERT INTO MOBILE (ID, MODELNAME, OS, BRAND) VALUES (5, 'One Plus 6', 'Android', 'One Plus')
INSERT INTO MOBILE (ID, MODELNAME, OS, BRAND) VALUES (6, 'O8', 'Android', 'Oppo')
INSERT INTO MOBILE (ID, MODELNAME, OS, BRAND) VALUES (7, 'V5', 'Android', 'Vivo')
INSERT INTO MOBILE (ID, MODELNAME, OS, BRAND) VALUES (8, 'IPhone X', 'iOS', 'Apple')